# Generated by Django 5.0.6 on 2024-06-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_blog_mini_description_blog_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
